-- Create Dimension Tables
CREATE TABLE dim_patient (
    patient_id BIGINT PRIMARY KEY,
    age INT,
    postcode TEXT,
    patient_surname TEXT,
    patient_givenname TEXT,
    date_of_birth TIMESTAMP,
    date_of_death TIMESTAMP,
    registration_guid UUID,
    gender TEXT
);

CREATE TABLE dim_clinical_codes (
    refset_simple_id BIGINT,
    parent_code_id BIGINT,
    code_id BIGINT PRIMARY KEY,
    snomed_concept_id BIGINT,
    emis_term TEXT
);

-- Create Fact Tables
CREATE TABLE dim_observation (
    abnormal BOOLEAN,
    emis_code_id BIGINT,
    comparator TEXT,
    confidential_flag BOOLEAN,
    confidential_patient_flag BOOLEAN,
    consultation_source_emis_code_id BIGINT,
    consultation_source_emis_original_term TEXT,
    document_guid UUID,
    dummy_patient_flag BOOLEAN,
    effective_date TIMESTAMP,
    effective_date_precision TEXT,
    emis_enteredby_userinrole_guid UUID,
    emis_episodicity BIGINT,
    end_date TIMESTAMP,
    fhir_episodicity TEXT,
    emis_observation_guid UUID,
    exa_observation_guid UUID,
    fhir_interpretation_code TEXT,
    is_parent_flag BOOLEAN,
    non_regular_and_current_active_flag BOOLEAN,
    emis_observation_id BIGINT PRIMARY KEY,
    observation_type TEXT,
    emis_observationtypeid BIGINT,
    opt_out_93c1_flag BOOLEAN,
    opt_out_9nd19nu09nu4_flag BOOLEAN,
    opt_out_9nd19nu0_flag BOOLEAN,
    opt_out_9nu0_flag BOOLEAN,
    other_code TEXT,
    other_code_system TEXT,
    other_display TEXT,
    range_lower DOUBLE PRECISION,
    range_upper DOUBLE PRECISION,
    readv2_code TEXT,
    recorded_date TIMESTAMP,
    registration_guid UUID REFERENCES dim_patient(registration_guid),
    regular_and_current_active_flag BOOLEAN,
    regular_current_active_and_inactive_flag BOOLEAN,
    regular_patient_flag BOOLEAN,
    emis_original_term TEXT,
    sensitive_flag BOOLEAN,
    sensitive_patient_flag BOOLEAN,
    snomed_concept_id BIGINT REFERENCES dim_clinical_codes(snomed_concept_id),
    snomed_description_id BIGINT,
    emis_parent_observation_guid UUID,
    exa_parent_observation_guid UUID,
    uom TEXT,
    uom_ucum TEXT,
    user_selected DOUBLE PRECISION,
    numericvalue DOUBLE PRECISION,
    value_pq_2 DOUBLE PRECISION
);

CREATE TABLE dim_medication (
    nhs_prescribing_agency TEXT,
    emis_drug_guid UUID,
    authorisedissues_authorised_date TIMESTAMP,
    authorisedissues_first_issue_date TIMESTAMP,
    cancellation_reason TEXT,
    emis_code_id BIGINT,
    confidential_flag BOOLEAN,
    consultation_source_emis_code_id DOUBLE PRECISION,
    consultation_source_emis_original_term TEXT,
    dose TEXT,
    emis_medication_status DOUBLE PRECISION,
    dummy_patient_flag BOOLEAN,
    duration_in_days BIGINT,
    duration_uom TEXT,
    effective_date TIMESTAMP,
    effective_date_precision TEXT,
    emis_issue_method TEXT,
    emis_mostrecent_issue_date TIMESTAMP,
    emis_prescription_type TEXT,
    emis_registration_organisation_guid UUID,
    emis_encounter_guid UUID,
    exa_encounter_guid UUID,
    end_date TIMESTAMP,
    emis_enteredby_userinrole_guid UUID,
    exa_prescription_guid DOUBLE PRECISION,
    estimated_nhs_cost DOUBLE PRECISION,
    exa_drug_guid UUID,
    medication_guid UUID PRIMARY KEY,
    exa_medication_guid UUID,
    fhir_medication_intent TEXT,
    exa_mostrecent_issue_date TIMESTAMP,
    max_nextissue_days DOUBLE PRECISION,
    min_nextissue_days DOUBLE PRECISION,
    non_regular_and_current_active_flag BOOLEAN,
    number_authorised DOUBLE PRECISION,
    number_of_issues DOUBLE PRECISION,
    opt_out_93c1_flag BOOLEAN,
    opt_out_9nd19nu09nu4_flag BOOLEAN,
    opt_out_9nd19nu0_flag BOOLEAN,
    opt_out_9nu0_flag BOOLEAN,
    emis_medication_organisation_guid UUID,
    other_code TEXT,
    other_code_system TEXT,
    prescribed_as_contraceptive_flag BOOLEAN,
    privately_prescribed_flag BOOLEAN,
    quantity DOUBLE PRECISION,
    recorded_date TIMESTAMP,
    registration_guid UUID REFERENCES dim_patient(registration_guid),
    regular_and_current_active_flag BOOLEAN,
    regular_current_active_and_inactive_flag BOOLEAN,
    regular_patient_flag BOOLEAN,
    reimburse_type BIGINT,
    review_date TIMESTAMP,
    emis_original_term TEXT,
    sensitive_flag BOOLEAN,
    sensitive_patient_flag BOOLEAN,
    snomed_concept_id BIGINT REFERENCES dim_clinical_codes(snomed_concept_id),
    snomed_description_id BIGINT,
    fhir_medication_status TEXT,
    cancellation_date TIMESTAMP,
    nhs_prescription_type TEXT,
    uom TEXT,
    uom_dmd DOUBLE PRECISION
);
